// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import './globals.css';
import Navbar from '@/components/Navbar';
import type { Metadata } from 'next';
import { Inter, 
  // Inconsolata, 
  //Roboto 
} from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
// const inconsolata = Inconsolata({ subsets: ['latin'] });
// const roboto = Roboto({ subsets: ['latin'], weight:['400'] });

export const metadata: Metadata = {
  title: 'Next Tutorial',
  description: 'A Next.js project with TypeScript and TailwindCSS.',
  keywords: 'Next.js, Typescript, TailwindCSS',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        <main className='flex min-w-[90%] mx-auto py-10 justify-center'>{children}</main>
      </body>
    </html>
  );
}